csv-core: change version to 0.0.99
cargo vendor on anki currently fails as follow:
error: failed to sync

Caused by:
  found duplicate version of package `csv-core v0.1.10` vendored from two sources:

  	source 1: registry `crates-io`
  	source 2: https://github.com/ankitects/rust-csv.git?rev=1c9d3aab6f79a7d815c69f925a46a4590c115f90#1c9d3aab

Because csv-core is included twice in the dependency tree:
├── csv v1.1.6 (https://github.com/ankitects/rust-csv.git?rev=1c9d3aab6f79a7d815c69f925a46a4590c115f90#1c9d3aab)
│   ├── csv-core v0.1.10 (https://github.com/ankitects/rust-csv.git?rev=1c9d3aab6f79a7d815c69f925a46a4590c115f90#1c9d3aab)
├── fsrs-optimizer v0.1.0 (https://github.com/open-spaced-repetition/fsrs-optimizer-rs?rev=e0b15cce555a94de6fdaa4bf1e096d19704a397d#e0b15cce)
│   ├── burn v0.9.0 (https://github.com/burn-rs/burn.git?rev=36446e8d35694a9158f97e85e44b84544b8c4afb#36446e8d)
│   │   ├── burn-core v0.9.0 (https://github.com/burn-rs/burn.git?rev=36446e8d35694a9158f97e85e44b84544b8c4afb#36446e8d)
│   │   │   ├── burn-dataset v0.9.0 (https://github.com/burn-rs/burn.git?rev=36446e8d35694a9158f97e85e44b84544b8c4afb#36446e8d)
│   │   │   │   ├── csv v1.2.2
│   │   │   │   │   ├── csv-core v0.1.10

Until something similar to commit 1c9d3aab6f79 ("Automatically escape
fields that contain the comment character") makes it in an upstream
release, take the easy way out and just make sure the versions don't
conflict for cargo vendor.